from abc import ABC, abstractmethod
class OTPProvider(ABC):
    @abstractmethod
    def send_otp(self, phone: str) -> dict: ...
    @abstractmethod
    def verify_otp(self, phone: str, code: str) -> bool: ...
    @abstractmethod
    def resend_otp(self, phone: str) -> dict: ...